### ISSUE TITLE
Missing Miniconda.tar

### ISSUE THREAD

**Issue by strideynet** [blockchain-etl/bitcoin-etl-airflow#3]
https://github.com/blockchain-etl/bitcoin-etl-airflow/blob/master/dags/bitcoinetl/build_export_dag.py#L44

Seems to refer to a miniconda.tar that comes with the dependencies already installed. I feel like I'm missing something but without documentation it's hard to work this out.

**Comment by medvedev1088** [comment]
Try something like this:

```
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
bash Miniconda3-latest-Linux-x86_64.sh

path_to_miniconda/bin/python -m pip install bitcoin-etl==1.2.1

tar cvf miniconda.tar path_to_miniconda
```
