### ISSUE TITLE
Load DAG Enrich Blocks Task Fails

### ISSUE THREAD

**Issue by oswidan97** [blockchain-etl/bitcoin-etl-airflow#7]
The `bitcoin_load_dag` 's `enrich_blocks` task is failing with the following error
```
AttributeError: 'dict' object has no attribute 'from_string'
```
I am using the following versions
```
AIRFLOW_VERSION=1.10.15
COMPOSER_VERSION=1.17.6
```
The problem is with this line `sql = kwargs['task'].render_template('', sql_template, template_context)` and changing it to  `sql = kwargs['task'].render_template(sql_template, template_context)` solves the issue. I guess its a versions problem so what versions should be used to avoid this issue ?

**Comment by medvedev1088** [comment]
Correct it's the outdated composer version that's no longer supported. Some changes from the ethereum DAGs https://github.com/blockchain-etl/ethereum-etl-airflow/pull/272/files should be ported here to support the new version
